# Generated by Django 3.1 on 2020-10-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('stat', 'Statistics'), ('cs', 'Computer Science'), ('ds', 'data science'), ('com', 'communications'), ('other', 'other')], default='other', max_length=8)),
                ('users', models.ManyToManyField(blank=True, related_name='course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_version', models.CharField(choices=[('1', 'Starting test'), ('2', 'second test'), ('3', 'final test')], default='1', max_length=8)),
                ('result', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='finalProject.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
