# Generated by Django 3.1 on 2020-10-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0002_course_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('stat', 'Statistics'), ('cs', 'Computer Science'), ('ds', 'Data Science'), ('com', 'Communications'), ('other', 'other')], default='other', max_length=8),
        ),
    ]
