# Generated by Django 3.1 on 2020-10-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0004_auto_20201025_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('NA', 'NA')], default='NA', max_length=2)),
                ('question2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('NA', 'NA')], default='NA', max_length=2)),
                ('question3', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('NA', 'NA')], default='NA', max_length=2)),
                ('question4', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('NA', 'NA')], default='NA', max_length=2)),
                ('question5', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('NA', 'NA')], default='NA', max_length=2)),
                ('question6', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('NA', 'NA')], default='NA', max_length=2)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='finalProject.test')),
            ],
        ),
    ]
