# Generated by Django 3.1 on 2020-10-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0005_testdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Statistics', 'Statistics'), ('Computer Science', 'Computer Science'), ('Data Science', 'Data Science'), ('Communications', 'Communications'), ('other', 'other')], default='other', max_length=16, unique=True),
        ),
    ]
