# Generated by Django 3.1 on 2020-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0006_auto_20201029_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default="We hope you'll enjoy and learn in this course"),
        ),
    ]
